// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftVrXSHpA0KVC8yfEf2TcdVEE8yrx_Ig',
    appId: '1:442984743193:web:0d851690456129b8b10588',
    messagingSenderId: '442984743193',
    projectId: 'memory-book-c1f7d',
    authDomain: 'memory-book-c1f7d.firebaseapp.com',
    storageBucket: 'memory-book-c1f7d.appspot.com',
    measurementId: 'G-FSS33682E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5hvnNARrieIvc4sR1KvvKm8GM0Ylr-Y',
    appId: '1:442984743193:android:ade61ed7a64fe428b10588',
    messagingSenderId: '442984743193',
    projectId: 'memory-book-c1f7d',
    storageBucket: 'memory-book-c1f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0liN5oPExDtyeqGmY8RRdnqfG9RBKrk',
    appId: '1:442984743193:ios:6f6e23937ec86600b10588',
    messagingSenderId: '442984743193',
    projectId: 'memory-book-c1f7d',
    storageBucket: 'memory-book-c1f7d.appspot.com',
    iosClientId: '442984743193-2g5scc2lh87r0kils1d1mg080h6u4bvh.apps.googleusercontent.com',
    iosBundleId: 'com.appfactory.memorybook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0liN5oPExDtyeqGmY8RRdnqfG9RBKrk',
    appId: '1:442984743193:ios:6f6e23937ec86600b10588',
    messagingSenderId: '442984743193',
    projectId: 'memory-book-c1f7d',
    storageBucket: 'memory-book-c1f7d.appspot.com',
    iosClientId: '442984743193-2g5scc2lh87r0kils1d1mg080h6u4bvh.apps.googleusercontent.com',
    iosBundleId: 'com.appfactory.memorybook',
  );
}
